tap "deskflow/tap"
tap "felixkratz/formulae"
tap "koekeishiya/formulae"
tap "lucaspickering/tap"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Core application library for C
brew "glib"
# Cut, copy, and paste anything, anywhere, all from the terminal
brew "clipboard"
# Cross-platform make
brew "cmake"
# Disk Usage/Free Utility - a better 'df' alternative
brew "duf"
# Static file server
brew "dufs"
# Modern, maintained replacement for ls
brew "eza"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# OpenType text shaping engine
brew "harfbuzz"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Improved top (interactive process viewer)
brew "htop"
# Update of iperf: measures TCP, UDP, and SCTP bandwidth
brew "iperf3"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Simple terminal UI for git commands
brew "lazygit"
# Graphical front-end for GCC's coverage testing tool (gcov)
brew "lcov"
# Next-gen compiler infrastructure
brew "llvm"
# Mac App Store command-line interface
brew "mas"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Fast, disk space efficient package manager
brew "pnpm"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Feature-rich console based todo list manager
brew "task"
# TCP connect to the given IP/port combo
brew "tcping"
# Modernized, complete, self-contained TeX/LaTeX engine
brew "tectonic"
# Simplified and community-driven man pages
brew "tldr"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Markup-based typesetting system
brew "typst"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Custom macOS statusbar with shell plugin, interaction and graph support
brew "felixkratz/formulae/sketchybar"
# A tiling window manager for macOS based on binary space partitioning.
brew "koekeishiya/formulae/yabai"
# Desktop client that supports multiple LLM providers
cask "cherry-studio"
# Continuation of Clash Verge - A Clash Meta GUI based on Tauri
cask "clash-verge-rev"
# Mouse and keyboard sharing utility
cask "deskflow"
# Voice and text chat software
cask "discord"
# Dictionary and translator app
cask "easydict"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-sf-pro"
cask "font-source-code-pro"
# Web browser
cask "google-chrome"
# Free and open-source media player
cask "iina"
# Open-source cross-platform alternative to AirDrop
cask "localsend"
# Privacy-first, open-source platform for knowledge sharing and management
cask "logseq"
# Clipboard manager
cask "maccy"
# Remote desktop client
cask "microsoft-remote-desktop"
# Intercept, modify, replay, save HTTP/S traffic
cask "mitmproxy"
# Open source virtual/remote desktop application
cask "rustdesk"
# Tool that provides consistent, highly configurable symbols for apps
cask "sf-symbols"
# Mesh VPN based on WireGuard
cask "tailscale-app"
# Messaging app with a focus on speed and security
cask "telegram"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
# Mind mapping and brainstorming tool
cask "xmind"
# Open-source version of the X.Org X Window System
cask "xquartz"
# Multiplayer code editor
cask "zed"
# Collect, organise, cite, and share research sources
cask "zotero"
mas "QQ", id: 451108668
mas "The Unarchiver", id: 425424353
mas "企业微信", id: 1189898970
mas "微信", id: 836500024
mas "腾讯会议", id: 1484048379
vscode "adpyke.codesnap"
vscode "britesnow.vscode-toggle-quotes"
vscode "continue.continue"
vscode "cweijan.dbclient-jdbc"
vscode "cweijan.vscode-mysql-client2"
vscode "damiankoper.gdb-debug"
vscode "danielpinto8zz6.c-cpp-compile-run"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "donjayamanne.githistory"
vscode "dotjoshjohnson.xml"
vscode "dvirtz.parquet-viewer"
vscode "esbenp.prettier-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.remotehub"
vscode "gruntfuggly.todo-tree"
vscode "hediet.debug-visualizer"
vscode "hediet.vscode-drawio"
vscode "hnw.vscode-auto-open-markdown-preview"
vscode "humao.rest-client"
vscode "james-yu.latex-workshop"
vscode "jeff-hykin.better-cpp-syntax"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "llvm-vs-code-extensions.vscode-clangd"
vscode "maattdd.gitless"
vscode "mindaro-dev.file-downloader"
vscode "mkloubert.vs-rest-api"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-zh-hans"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.live-server"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "mshr-h.veriloghdl"
vscode "mutantdino.resourcemonitor"
vscode "nvarner.typst-lsp"
vscode "oderwat.indent-rainbow"
vscode "orangex4.hsnips"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "sandcastle.vscode-open"
vscode "saoudrizwan.claude-dev"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "simonsiefke.svg-preview"
vscode "streetsidesoftware.code-spell-checker"
vscode "tauri-apps.tauri-vscode"
vscode "techer.open-in-browser"
vscode "tomoki1207.pdf"
vscode "usernamehw.errorlens"
vscode "vadimcn.vscode-lldb"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscode-icons-team.vscode-icons"
vscode "vscodevim.vim"
vscode "wushuaibuaa.autocomplete-english-word"
vscode "yzhang.markdown-all-in-one"
vscode "zaaack.markdown-editor"
vscode "zhuangtongfa.material-theme"
